# -*- coding: utf-8 -*-
"""The painters help.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDvjycVsflp5UGFYXsGRvBzNRSATakue
"""

# the painters helper display the options to the user
print("1. cost of painting a conical surface"
"2. cost of painting a cubical surace "
"3cost of painting a cuboidal surface"
"4. cost of painting a spherical surface"
"5. calculate the cost of painting a cylindrical surface")

# Get input from the user to select the options

a=int(input("Enter the options from 1 to 5 "))

#select the correct formula for the selected option
#for cone
if a==1:
  b=float(input("Radius of the cone in metre"))
  c=float(input("Height of the cone in metre"))
  area_to_paint = 3.14 * b * c # Assuming this is the intended area formula for cone
  print(area_to_paint,"area to paint in metre")
  k=float(input("cost of painting per metre"))
  total_cost = k * area_to_paint
  print(total_cost)

# for cubical
elif a==2:
  d=float(input("Length of the cubical surface in metre"))
  area_to_paint = 4*d**2 # Assuming 4 sides of a cube are painted
  print(area_to_paint,"Area to paint in metre")
  k=float(input("cost of painting per metre"))
  total_cost = k * area_to_paint
  print(total_cost)
#for cuboid
elif a==3:
  e=float(input("Length of the cuboidal surface in metre"))
  f=float(input("Width of the cuboidal surface in metre"))
  g=float(input("Height of the cuboid in metre"))
  area_to_paint = 2*g*(e+f) # Lateral surface area of cuboid
  print(area_to_paint,"Area to paint in metre")
  k=float(input("cost of painting per metre"))
  total_cost = k * area_to_paint
  print(total_cost)
#for sphere
elif a==4:
  h=float(input("Radius of the spherical surface in metre"))
  area_to_paint = 4*3.14*h**2
  print(area_to_paint,"Area to paint in metre")
  k=float(input("cost of painting per metre"))
  total_cost = k * area_to_paint
  print(total_cost)
#for cylinder
elif a==5:
  i=float(input("Radius of the cylindrical surface in metre"))
  j=float(input("Height of the cylindrical surface in metre"))
  area_to_paint = 2*3.14*i*(i+j) # Total surface area of cylinder
  print(area_to_paint,"Area to paint in metre")
  k=float(input("cost of painting per metre"))
  total_cost = k * area_to_paint
  print(total_cost)


#display thank you message
print("Thank you for using painters help")